/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esbarca;

/**
 *
 * @author studente_2
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    
    private int posX;
    private int posY; 
    
    public Finestra() {
        initComponents();
        TastoSu.setEnabled(false);
        TastoGiu.setEnabled(false);
        TastoDestra.setEnabled(false);
        TastoSinistra.setEnabled(false);
        this.posX = this.Barca.getX();
        this.posY = this.Barca.getY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannelloMare = new javax.swing.JPanel();
        Barca = new javax.swing.JLabel();
        BottoneAvvia = new javax.swing.JButton();
        BottoneFerma = new javax.swing.JButton();
        TastoGiu = new javax.swing.JButton();
        TastoDestra = new javax.swing.JButton();
        TastoSinistra = new javax.swing.JButton();
        TastoSu = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        TestoVelocita = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PannelloMare.setBackground(new java.awt.Color(153, 204, 255));

        Barca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esbarca/sailboat_38507.png"))); // NOI18N

        javax.swing.GroupLayout PannelloMareLayout = new javax.swing.GroupLayout(PannelloMare);
        PannelloMare.setLayout(PannelloMareLayout);
        PannelloMareLayout.setHorizontalGroup(
            PannelloMareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloMareLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Barca)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        PannelloMareLayout.setVerticalGroup(
            PannelloMareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelloMareLayout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(Barca)
                .addGap(23, 23, 23))
        );

        BottoneAvvia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BottoneAvvia.setText("AVVIA");
        BottoneAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneAvviaActionPerformed(evt);
            }
        });

        BottoneFerma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BottoneFerma.setText("FERMA");
        BottoneFerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneFermaActionPerformed(evt);
            }
        });

        TastoGiu.setText("↓");
        TastoGiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TastoGiuActionPerformed(evt);
            }
        });

        TastoDestra.setText("→");
        TastoDestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TastoDestraActionPerformed(evt);
            }
        });

        TastoSinistra.setText("←");
        TastoSinistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TastoSinistraActionPerformed(evt);
            }
        });

        TastoSu.setText("↑");
        TastoSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TastoSuActionPerformed(evt);
            }
        });

        jSlider1.setMaximum(20);
        jSlider1.setMinimum(5);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(5);

        TestoVelocita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TestoVelocita.setText("--Cambia velocità--");

        jLabel1.setText("-- Properzi Mirea -- es. Barca -- 06/04/17 -- ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TastoSu)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TastoSinistra)
                                        .addGap(18, 18, 18)
                                        .addComponent(TastoGiu)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TastoDestra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TestoVelocita)
                                        .addGap(19, 19, 19))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BottoneAvvia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BottoneFerma))
                            .addComponent(PannelloMare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BottoneAvvia)
                    .addComponent(BottoneFerma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PannelloMare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(TastoSu)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TastoGiu)
                            .addComponent(TastoDestra)
                            .addComponent(TastoSinistra)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TestoVelocita)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneAvviaActionPerformed
        TastoSu.setEnabled(true);
        TastoGiu.setEnabled(true);
        TastoDestra.setEnabled(true);
        TastoSinistra.setEnabled(true);
    }//GEN-LAST:event_BottoneAvviaActionPerformed

    private void BottoneFermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneFermaActionPerformed
        TastoSu.setEnabled(false);
        TastoGiu.setEnabled(false);
        TastoDestra.setEnabled(false);
        TastoSinistra.setEnabled(false);
        Barca.setLocation(posX,posY);
    }//GEN-LAST:event_BottoneFermaActionPerformed

    private void TastoSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TastoSuActionPerformed
        int x = Barca.getX();
        int y = Barca.getY();
        int s = jSlider1.getValue();
        Barca.setLocation(x, y-s);
    }//GEN-LAST:event_TastoSuActionPerformed

    private void TastoGiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TastoGiuActionPerformed
        int x = Barca.getX();
        int y = Barca.getY();
        int s = jSlider1.getValue();
        Barca.setLocation(x, y+s);
    }//GEN-LAST:event_TastoGiuActionPerformed

    private void TastoSinistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TastoSinistraActionPerformed
        int x = Barca.getX();
        int y = Barca.getY();
        int s = jSlider1.getValue();
        Barca.setLocation(x-s, y);
    }//GEN-LAST:event_TastoSinistraActionPerformed

    private void TastoDestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TastoDestraActionPerformed
        int x = Barca.getX();
        int y = Barca.getY();
        int s = jSlider1.getValue();
        Barca.setLocation(x+s, y);
    }//GEN-LAST:event_TastoDestraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barca;
    private javax.swing.JButton BottoneAvvia;
    private javax.swing.JButton BottoneFerma;
    private javax.swing.JPanel PannelloMare;
    private javax.swing.JButton TastoDestra;
    private javax.swing.JButton TastoGiu;
    private javax.swing.JButton TastoSinistra;
    private javax.swing.JButton TastoSu;
    private javax.swing.JLabel TestoVelocita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
